# Generated by Django 6.0.1 on 2026-01-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_onlineuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineuser',
            name='age',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='onlineuser',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
