# Generated by Django 6.0.1 on 2026-01-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
