# Generated by Django 6.0.1 on 2026-01-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chatmessage_is_read_alter_chatmessage_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_typing',
            field=models.BooleanField(default=False),
        ),
    ]
