# Generated by Django 6.0.1 on 2026-01-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_profile_is_typing'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
