# Generated by Django 6.0.1 on 2026-01-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_profile_age_profile_is_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_guest',
            field=models.BooleanField(default=True),
        ),
    ]
