# Generated by Django 6.0.1 on 2026-01-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_admininquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badge',
            field=models.CharField(choices=[('Member', 'Member'), ('Admin', '👑 Admin'), ('VIP', '💎 VIP'), ('Verified', '✅ Verified'), ('Bot', '🤖 Bot')], default='Member', max_length=20),
        ),
    ]
